---
__jenkins_repo_url: deb https://pkg.jenkins.io/debian-stable binary/
__jenkins_repo_key_url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
__jenkins_pkg_url: https://pkg.jenkins.io/debian/binary
